/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { CustomerSession } from "./customersession.js";
import { Downloadables } from "./downloadables.js";
import { SpaireBenefitGrants } from "./spairebenefitgrants.js";
import { SpaireCustomerMeters } from "./spairecustomermeters.js";
import { SpaireCustomers } from "./spairecustomers.js";
import { SpaireLicenseKeys } from "./spairelicensekeys.js";
import { SpaireMembers } from "./spairemembers.js";
import { SpaireOrders } from "./spaireorders.js";
import { SpaireOrganizations } from "./spaireorganizations.js";
import { SpaireSubscriptions } from "./spairesubscriptions.js";
import { Seats } from "./seats.js";
import { Wallets } from "./wallets.js";

export class CustomerPortal extends ClientSDK {
  private _benefitGrants?: SpaireBenefitGrants;
  get benefitGrants(): SpaireBenefitGrants {
    return (this._benefitGrants ??= new SpaireBenefitGrants(this._options));
  }

  private _customers?: SpaireCustomers;
  get customers(): SpaireCustomers {
    return (this._customers ??= new SpaireCustomers(this._options));
  }

  private _customerMeters?: SpaireCustomerMeters;
  get customerMeters(): SpaireCustomerMeters {
    return (this._customerMeters ??= new SpaireCustomerMeters(this._options));
  }

  private _seats?: Seats;
  get seats(): Seats {
    return (this._seats ??= new Seats(this._options));
  }

  private _customerSession?: CustomerSession;
  get customerSession(): CustomerSession {
    return (this._customerSession ??= new CustomerSession(this._options));
  }

  private _downloadables?: Downloadables;
  get downloadables(): Downloadables {
    return (this._downloadables ??= new Downloadables(this._options));
  }

  private _licenseKeys?: SpaireLicenseKeys;
  get licenseKeys(): SpaireLicenseKeys {
    return (this._licenseKeys ??= new SpaireLicenseKeys(this._options));
  }

  private _members?: SpaireMembers;
  get members(): SpaireMembers {
    return (this._members ??= new SpaireMembers(this._options));
  }

  private _orders?: SpaireOrders;
  get orders(): SpaireOrders {
    return (this._orders ??= new SpaireOrders(this._options));
  }

  private _organizations?: SpaireOrganizations;
  get organizations(): SpaireOrganizations {
    return (this._organizations ??= new SpaireOrganizations(this._options));
  }

  private _subscriptions?: SpaireSubscriptions;
  get subscriptions(): SpaireSubscriptions {
    return (this._subscriptions ??= new SpaireSubscriptions(this._options));
  }

  private _wallets?: Wallets;
  get wallets(): Wallets {
    return (this._wallets ??= new Wallets(this._options));
  }
}
