/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @spaire/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx organizationsList.example.ts
 */

import { Spaire } from "@spaire/sdk";

const spaire = new Spaire({
  accessToken: process.env["SPAIRE_ACCESS_TOKEN"] ?? "",
});

async function main() {
  const result = await spaire.organizations.list({});

  for await (const page of result) {
    console.log(page);
  }
}

main().catch(console.error);
